"""add spanish note templates

Revision ID: 4fc315ec92bc
Revises: c2a44009a4ec
Create Date: 2026-07-21 09:23:29.512995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fc315ec92bc'
down_revision: Union[str, None] = 'c2a44009a4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grading_company_tolerance_rules', sa.Column('note_template_es', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grading_company_tolerance_rules', 'note_template_es')
    # ### end Alembic commands ###
