"""add scan_images.crop_points

Revision ID: a19f7c2e5b3d
Revises: 4fc315ec92bc
Create Date: 2026-07-24 00:00:00.000000

"""
import json
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'a19f7c2e5b3d'
down_revision: Union[str, None] = '4fc315ec92bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scan_images', sa.Column('crop_points', postgresql.JSONB(), nullable=True))
    # ### end Alembic commands ###

    # Backfill crop_points for scans uploaded before this migration by
    # auto-detecting the card boundary in the already-stored file, so
    # pre-existing rows don't silently stall once analysis starts requiring
    # crop_points to be set (see zgrader.worker.watcher._confirmed_sides).
    # A row whose file is missing/unreadable is left NULL -- same failure
    # mode as today, just surfaced later instead of at migration time.
    from zgrader.analysis import preprocessing

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id, file_path FROM scan_images")).fetchall()
    for row in rows:
        try:
            image = preprocessing.load_image(row.file_path)
            box, _info = preprocessing.detect_boundary(image)
        except Exception:
            continue
        conn.execute(
            sa.text("UPDATE scan_images SET crop_points = :points WHERE id = :id"),
            {"points": json.dumps(box.tolist()), "id": row.id},
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_images', 'crop_points')
    # ### end Alembic commands ###
