"""initial schema

Revision ID: ac0b8445171e
Revises: 
Create Date: 2026-07-18 18:07:08.397996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac0b8445171e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_dimension_references',
    sa.Column('game', sa.String(length=100), nullable=False),
    sa.Column('width_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('height_mm', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_dimension_references_game'), 'card_dimension_references', ['game'], unique=True)
    op.create_table('grading_company_tolerance_rules',
    sa.Column('company', sa.Enum('PSA', 'BGS', 'CGC', 'TAG', name='grading_company'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('metric_key', sa.String(length=100), nullable=False),
    sa.Column('thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('note_template', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('auto_publish_default', sa.Boolean(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=False),
    sa.Column('business_logo_path', sa.String(length=1024), nullable=True),
    sa.Column('business_contact', sa.String(length=500), nullable=True),
    sa.Column('disclaimer_text', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('role', sa.Enum('client', 'operator', name='user_role'), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('submissions',
    sa.Column('submission_code', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('batch_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('created', 'awaiting_scans', 'processing', 'draft_ready', 'approved', 'published', 'error', name='submission_status'), nullable=False),
    sa.Column('auto_publish', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_submission_code'), 'submissions', ['submission_code'], unique=True)
    op.create_table('analysis_results',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('centering', 'corners', 'edges', 'surface', name='analysis_category'), nullable=False),
    sa.Column('side', sa.Enum('front', 'back', 'combined', name='analysis_side'), nullable=False),
    sa.Column('raw_score', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('measurements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('annotated_image_path', sa.String(length=1024), nullable=True),
    sa.Column('flags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('submission_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('game', sa.String(length=100), nullable=False),
    sa.Column('set_name', sa.String(length=200), nullable=True),
    sa.Column('card_name', sa.String(length=200), nullable=False),
    sa.Column('card_number', sa.String(length=50), nullable=True),
    sa.Column('foil', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('grading_company_comparisons',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('company', sa.Enum('PSA', 'BGS', 'CGC', 'TAG', name='grading_company'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.Enum('none', 'minor', 'major', name='tolerance_severity'), nullable=False),
    sa.Column('contention_note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'approved', 'published', name='report_status'), nullable=False),
    sa.Column('pdf_path', sa.String(length=1024), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approved_by_user_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_images',
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.Enum('front', 'back', name='scan_side'), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scan_images')
    op.drop_table('reports')
    op.drop_table('grading_company_comparisons')
    op.drop_table('cards')
    op.drop_table('audit_logs')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_submissions_submission_code'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('grading_company_tolerance_rules')
    op.drop_index(op.f('ix_card_dimension_references_game'), table_name='card_dimension_references')
    op.drop_table('card_dimension_references')
    # ### end Alembic commands ###
