"""add submission language

Revision ID: c2a44009a4ec
Revises: e02560c43629
Create Date: 2026-07-21 09:11:37.949172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2a44009a4ec'
down_revision: Union[str, None] = 'e02560c43629'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    submission_language = sa.Enum('en', 'es', name='submission_language')
    submission_language.create(op.get_bind(), checkfirst=True)
    op.add_column('submissions', sa.Column('language', submission_language, server_default='en', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'language')
    # ### end Alembic commands ###
    sa.Enum(name='submission_language').drop(op.get_bind(), checkfirst=True)
