"""phase2: user verification token, nullable audit log actor

Revision ID: e02560c43629
Revises: ac0b8445171e
Create Date: 2026-07-18 19:51:08.596108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e02560c43629'
down_revision: Union[str, None] = 'ac0b8445171e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('verification_token', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verification_token')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
